name: deployment
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      repository-branch:
        description: The branch to checkout
        default: main
        required: true
      app-name:
        description: The name of the application that will be created in Wayfinder
        default: app-name-placeholder
        required: true
      app-environment-name:
        description: The name of the application environment that will be created in Wayfinder
        default: dev
        required: true

env:
  WAYFINDER_TOKEN: ${{ secrets.WAYFINDER_TOKEN }}
  WAYFINDER_SERVER: ${{ vars.WAYFINDER_SERVER }}
  WAYFINDER_WORKSPACE: ${{ vars.WAYFINDER_WORKSPACE || 'workspace-placeholder' }}
  APPLICATION_NAME: ${{ inputs.app-name || 'app-name-placeholder' }}
  APP_ENVIRONMENT_NAME: ${{ inputs.app-environment-name || 'dev' }}
  INFRA_DIRECTORY: ${{ inputs.infra-directory || 'infra' }}


jobs:
  build_docker:
    # needs: unit_test
    runs-on: ubuntu-latest
    # if: (github.ref == 'refs/heads/master')
    timeout-minutes: 60
    outputs:
      sha-tag: sha-${{ github.sha }}
      ref-tag: sha-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3.5.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          
      - name: Build tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ github.ref }},enable={{is_default_branch}}
            type=raw,value=${{ github.sha }},prefix=sha-,enable={{is_default_branch}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        id: docker-digest
        with:
          push: true
          cache-from: |
            ghcr.io/${{ github.repository }}:latest
          file: source/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
      
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build_docker
    container:
      env:
        WAYFINDER_TOKEN:  ${{ env.WAYFINDER_TOKEN }}
        WAYFINDER_SERVER:  ${{ env.WAYFINDER_SERVER }}
        WAYFINDER_WORKSPACE:  ${{ env.WAYFINDER_WORKSPACE }}
        APPLICATION_NAME: ${{ env.APPLICATION_NAME }}
        APP_ENVIRONMENT_NAME:  ${{ env.APP_ENVIRONMENT_NAME }}
        INFRA_DIRECTORY:  ${{ env.INFRA_DIRECTORY }}
      image: quay.io/appvia-wayfinder/wftoolbox:v2.2.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.repository-branch || 'main' }}   
 
      - name: Create Application & Application Environment
        run: wf apply -f "${INFRA_DIRECTORY}/" --wait-for-ready ${{ inputs.app-env-wait-time || '1m' }}

      - name: deploy Application
        run: wf deploy app ${APPLICATION_NAME} ${APP_ENVIRONMENT_NAME} --image-tag ${{ needs.build_docker.outputs.sha-tag }}
      
      - name: patch imagePullSecret
        run: |
          # We need to give kubelet credentials to pull images from ghcr.io
          # This needs to be done using kubectl at the moment
          # but in a future version of Wayfinder we will be able to do this using wf
          namespace=${WAYFINDER_WORKSPACE}-${APPLICATION_NAME}-${APP_ENVIRONMENT_NAME}
          wf access env ${APPLICATION_NAME} ${APP_ENVIRONMENT_NAME}
          
          # Get deployment name and add them to a list
          deployments_list=$(kubectl get deployments -n $namespace -o jsonpath='{.items[*].metadata.name}')
          
          # Loop through deployments
          for deployment in $deployments_list; do
              echo "$deployment"
              kubectl patch deployment "$deployment" -n "$namespace" --patch '{"spec":{"template":{"spec":{"imagePullSecrets":[{"name":"ghcr-login-secret"}]}}}}'
          done
          


      - name: get ingress
        run: |
          # get the ingress hostname
          kubectl get ingress 
